apiVersion: v1
kind: Secret
metadata:
  name: {{.Role}}-user-data-managed
  namespace: openshift-machine-api
  labels:
    "machineconfiguration.openshift.io/managed-ca-bundle-derived-from-configmap": ""
type: Opaque
data:
  disableTemplating: "dHJ1ZQo="
  userData: {{.PointerConfig}}
