mode: 0755
path: "/usr/local/bin/nmstate-configuration.sh"
contents:
  inline: |
    #!/bin/bash
    set -eux

    # Clean up old config on behalf of mtu-migration
    if ! systemctl -q is-enabled mtu-migration; then
      echo "Cleaning up left over mtu migration configuration"
      rm -rf /etc/cno/mtu-migration
    fi

    if [ -e /etc/nmstate/openshift/applied ]; then
      # Already done, don't apply again
      exit 0
    fi

    src_path="/etc/nmstate/openshift"
    dst_path="/etc/nmstate"
    hostname=$(hostname -s)
    hostname_file="${hostname}.yml"
    cluster_file="cluster.yml"
    config_file=""
    if [ -s "$src_path/$hostname_file" ]; then
      config_file=$hostname_file
    fi
    if [ -s "$src_path/$cluster_file" ]; then
      config_file=$cluster_file
    fi
    if [ -z $config_file ]; then
      # No config to apply
      exit 0
    fi

    if [ -e "$dst_path/$config_file" ]; then
      echo "ERROR: File $dst_path/$config_file exists. Refusing to overwrite."
      exit 1
    fi

    cp "$src_path/$config_file" /etc/nmstate
    touch /etc/nmstate/openshift/applied
